version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:20"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patches:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "08:40"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
